package com.fiberhome.fmdb.common;

/**
 * Created by sjj on 19/10/24
 */
public class SQLConstant {

    //用户自定义数据类型相关
    public static final String INSERT_UDCT_SQL = "INSERT INTO FMDB_CT VALUES (?,?,?,?,?);";
    public static final String SELECT_UDCT_SQL = "SELECT CT_NAME,WRITER,READ,BASE_TYPE FROM FMDB_CT WHERE CT_NAME = ? AND IS_UDCT = TRUE;";
    public static final String SELECT_ALL_UDCT_SQL = "SELECT CT_NAME,WRITER,READ,BASE_TYPE FROM FMDB_CT WHERE IS_UDCT = TRUE;";
    public static final String SELECT_BASETYPEBYACTYPE_SQL = "SELECT BASE_TYPE FROM FMDB_CT WHERE CT_NAME=?;";
    public static final String DELETE_UDCT_SQL = "DELETE FROM FMDB_CT WHERE CT_NAME = ?;";

    public static final String INSERT_DB_SQL = "INSERT INTO DBS VALUES (?,?);";
    public static final String DELETE_DB_SQL = "DELETE FROM DBS WHERE NAME=?;";
    public static final String LIST_DB_SQL = "SELECT NAME FROM DBS;";
    public static final String INSERT_TBL_SQL = "INSERT INTO TBLS VALUES (?,(SELECT DB_ID FROM DBS WHERE NAME = ?),?,(SELECT TYPE_ID FROM TBL_TYPE WHERE TYPE_NAME = ?),?,?,?,?,?);";
    public static final String INSERT_COL_SQL = "INSERT INTO COLUMNS VALUES (?,?,?,?,?,?,?,?,?,?,?);";
    public static final String INSERT_TBL_PARAM_SQL = "INSERT INTO TABLE_PARAMS VALUES (?,?,?);";
    public static final String DELETE_COLUMNS_SQL = "DELETE FROM COLUMNS WHERE TBL_ID= (SELECT TBL_ID FROM TBLS WHERE DB_ID=(SELECT DB_ID FROM DBS WHERE NAME=?) AND TBL_NAME=?) ;";
    public static final String DELETE_TBL_PARAM_SQL = "DELETE FROM TABLE_PARAMS WHERE TBL_ID= (SELECT TBL_ID FROM TBLS WHERE DB_ID=(SELECT DB_ID FROM DBS WHERE NAME=?) AND TBL_NAME=?);";
    public static final String DELETE_TBL_SQL = "DELETE FROM TBLS WHERE DB_ID=(SELECT DB_ID FROM DBS WHERE NAME=?) AND TBL_NAME=?;";

    public static final String SELECT_COLUMNS_SQL = "SELECT COMMENT,COLUMN_NAME,TYPE_NAME,INTEGER_IDX,ISNUL,PRECISION,SCALE FROM COLUMNS WHERE TBL_ID=(SELECT TBL_ID FROM TBLS WHERE DB_ID=(SELECT DB_ID FROM DBS WHERE NAME=?) AND TBL_NAME=?);";
    public static final String SELECT_COLUMN_NAME_SQL = "SELECT COLUMN_NAME FROM COLUMNS WHERE COL_ID = ?;";
    public static final String SELECT_TBL_PARAMS_SQL = "SELECT PARAM_KEY,PARAM_VALUE FROM TABLE_PARAMS WHERE TBL_ID=(SELECT TBL_ID FROM TBLS WHERE DB_ID=(SELECT DB_ID FROM DBS WHERE NAME=?) AND TBL_NAME=?);";
    public static final String SELECT_TBL_SQL = "SELECT PRIMARYKEYS,SORTFIELDS,SORTTYPE,COMPRESSTYPE,ORCSIZE FROM TBLS WHERE DB_ID=(SELECT DB_ID FROM DBS WHERE NAME=?) AND TBL_NAME=?";

    public static final String INSERT_IDXS_SQL = "INSERT INTO IDXS VALUES(?,(SELECT DB_ID FROM DBS WHERE NAME=?) ,?,(SELECT TBL_ID FROM TBLS WHERE DB_ID=(SELECT DB_ID FROM DBS WHERE NAME=?) AND TBL_NAME=?));";
    public static final String INSERT_IDX_PARAM_SQL = "INSERT INTO INDEX_PARAMS VALUES (?,?,?);";
    public static final String DELETE_IDX_PARAM_SQL = "DELETE FROM INDEX_PARAMS WHERE INDEX_ID=(SELECT TBL_ID FROM TBLS WHERE DB_ID=(SELECT DB_ID FROM DBS WHERE NAME = ?) AND TBL_NAME =?);";
    public static final String DELETE_IDX_SQL = "DELETE FROM IDXS WHERE DB_ID=(SELECT DB_ID FROM DBS WHERE NAME=?) AND INDEX_NAME=?;";
    //根据库名和索引名获取原始表名
    public static final String SELECT_ORITABLENAME_SQL = "SELECT TBL_NAME FROM TBLS WHERE TBL_ID=(SELECT ORIG_TBL_ID FROM IDXS WHERE DB_ID=(SELECT DB_ID FROM DBS WHERE NAME=?) AND INDEX_NAME=?);";
    //根据库名和索引名获取索引字段
    public static final String SELECT_INDEXCOL_SQL = "SELECT COLUMN_NAME FROM COLUMNS WHERE TBL_ID=(SELECT TBL_ID FROM TBLS WHERE DB_ID=(SELECT DB_ID FROM DBS WHERE NAME=?) AND TBL_NAME=?) AND STORAGE_TYPE='index';";
    //根据库名和索引名获取include字段
    public static final String SELECT_INCLUDECOL_SQL = "SELECT COLUMN_NAME FROM COLUMNS WHERE TBL_ID=(SELECT TBL_ID FROM TBLS WHERE DB_ID=(SELECT DB_ID FROM DBS WHERE NAME=?) AND TBL_NAME=?) AND STORAGE_TYPE='include';";
    //根据库名和索引名获取属性信息
    public static final String SELECT_IDX_PARAMS_SQL = "SELECT PARAM_KEY,PARAM_VALUE FROM INDEX_PARAMS WHERE INDEX_ID=(SELECT INDEX_ID FROM IDX WHERE DB_ID=(SELECT DB_ID FROM DBS WHERE NAME=?) AND INDEX_NAME=?);";
    //根据库名和表名获取所有的索引名
    public static final String SELECT_ALLINDEXS_SQL = "SELECT INDEX_NAME FROM IDXS WHERE ORIG_TBL_ID=(SELECT TBL_ID FROM TBLS WHERE DB_ID=(SELECT DB_ID FROM DBS WHERE NAME=?) AND TBL_NAME=?); ";
    //根据库名获取所有的表名
    public static final String SELECT_ALLTABLES_SQL = "SELECT TBL_NAME FROM TBLS WHERE DB_ID = (SELECT DB_ID FROM DBS WHERE NAME=?) AND TYPE_ID = (SELECT TYPE_ID FROM TBL_TYPE WHERE TYPE_NAME='table');";

    //插入manifest信息
    public static final String INSERT_MANIFEST_SQL = "INSERT INTO MANIFEST VALUES (?,?,?,?,?,?,?,?,?,?,?)";
    //获取已经存储的orc文件(DB_NAME_TBL_NAME_ORC_NAME)
    public static final String SELECT_MANIFEST_ORCNAME_SQL = "SELECT PART_NAME,ORC_NAME,COL_NAME,MIN,MAX,NOTNULLNUM,HASNULL,NULLNUM FROM MANIFEST WHERE DB_NAME=? AND TBL_NAME = ? and stat=true;";
    //根据库名和表名（真实表或索引表），删除对应的manifest信息
    public static final String DELETE_TBL_MANIFEST_SQL = "DELETE FROM MANIFEST WHERE DB_NAME=? AND TBL_NAME = ?;";
    //根据库名和表名查询相关的manifest信息
    public static final String SELECT_MANIFEST_SQL = "SELECT COL_NAME,MIN,MAX,ORC_NAME FROM MANIFEST WHERE ( DB_NAME=? AND TBL_NAME=?);";
    //查询所有的manifest信息
    public static final String SELECT_ALL_MANIFEST_SQL = "SELECT * FROM MANIFEST;";
    public static final String SELECT_DB_TBL_NAME = "SELECT DISTINCT DB_NAME,TBL_NAME FROM MANIFEST; ";
    public static final String UPDATE_ORC_MANIFEST_STAT = "UPDATE MANIFEST SET STAT = ? WHERE DB_NAME =? AND TBL_NAME=? AND PART_NAME=? AND ORC_NAME=?;";
    public static final String DELETE_ORC_MANIFEST = "DELETE FROM MANIFEST WHERE DB_NAME =? AND TBL_NAME=? AND PART_NAME=? AND ORC_NAME=?;";
    //插入分区信息
    public static final String INSERT_PARTITIONS_SQL = "INSERT INTO PARTITIONS VALUES(?,(SELECT COL_ID FROM COLUMNS WHERE TBL_ID=(SELECT TBL_ID FROM TBLS WHERE DB_ID =(SELECT DB_ID FROM DBS WHERE NAME=?) AND TBL_NAME=?) AND COLUMN_NAME=?),?,?);";
    //插入分区属性信息
    public static final String INSERT_PARTITIONS_PARAMS_SQL = "INSERT INTO PARTITION_PARAMS VALUES(?,?,?);";
    //删除分区属性信息
    public static final String DELETE_PARTITION_PARAMS_SQL = "DELETE FROM PARTITION_PARAMS WHERE PART_ID=(SELECT PART_ID FROM PARTITIONS WHERE COL_ID IN (SELECT COL_ID FROM COLUMNS WHERE TBL_ID=(SELECT TBL_ID FROM TBLS WHERE DB_ID =(SELECT DB_ID FROM DBS WHERE NAME=?) AND TBL_NAME=?) ));";
    //删除分区信息
    public static final String DELETE_PARTITIONS_SQL = "DELETE FROM PARTITIONS WHERE PART_ID=(SELECT PART_ID FROM PARTITIONS WHERE COL_ID IN (SELECT COL_ID FROM COLUMNS WHERE TBL_ID=(SELECT TBL_ID FROM TBLS WHERE DB_ID =(SELECT DB_ID FROM DBS WHERE NAME=?) AND TBL_NAME=?)))";
    //查询分区信息
    public static final String SELECT_PARTITIONS_SQL = "SELECT PART_ID,COL_ID,PART_TYPE,TTL FROM PARTITIONS WHERE COL_ID IN (SELECT COL_ID FROM COLUMNS WHERE TBL_ID=(SELECT TBL_ID FROM TBLS WHERE DB_ID =(SELECT DB_ID FROM DBS WHERE NAME=?) AND TBL_NAME=?));";
    //查询分区属性
    public static final String SELECT_PARTITION_PARAMS_SQL = "SELECT PARAM_KEY,PARAM_VALUE FROM PARTITION_PARAMS WHERE PART_ID = ?;";

    //数据量统计
    public static final String SELECT_TBLCOUNT_SQL = "SELECT TBLCOUNT FROM TBL_COUNT WHERE DB_NAME=? AND TBL_NAME=? AND PART_NAME=?;";
    public static final String INSERT_TBLCOUNT_SQL = "INSERT INTO TBL_COUNT VALUES(?,?,?,?);";
    public static final String UPDATE_TBLCOUNT_SQL = "UPDATE TBL_COUNT SET TBLCOUNT = ? WHERE DB_NAME=? AND TBL_NAME =? AND PART_NAME=?;";
    public static final String DELETE_TBLCOUNT_SQL = "DELETE FROM TBL_COUNT WHERE DB_NAME=? AND TBL_NAME=?;";

    // 统计信息相关
    public static final String INSERT_STAS_SQL = "INSERT INTO TBL_COLUMN_COUNT VALUES (?,?,?,?);";

    public static final  String TRUNCATE_SQL="TRUNCATE TABLE TBL_COLUMN_COUNT;";
}
